import type { Recommendation, RecommendationConfig, RecommendationContext, Topic, TopicProgress } from "./types";

type Candidate=Recommendation&{mastery:number;topicOrder:number;eventTime:number};
const progressFor=(topicId:string,progress:TopicProgress[])=>progress.find(item=>item.topicId===topicId);
const make=(topic:Topic,reasonCode:Recommendation["reasonCode"],priorityScore:number,reasonText:string,now:string,progress:TopicProgress[],supportingIds?:string[],eventTime=Number.MAX_SAFE_INTEGER):Candidate=>({id:`recommendation-${reasonCode}-${topic.id}`,topicId:topic.id,reasonCode,priorityScore,reasonText,estimatedMinutes:25,generatedAt:now,supportingIds,mastery:progressFor(topic.id,progress)?.masteryScore??0,topicOrder:topic.order,eventTime});

export function generateRecommendations(context:RecommendationContext,config:RecommendationConfig):Recommendation[]{
  const now=context.now??new Date().toISOString(),nowMs=Date.parse(now),candidates:Candidate[]=[];
  for(const event of context.events??[]){const start=Date.parse(event.start),days=(start-nowMs)/86_400_000;if(days>=0&&days<=config.upcomingEventWindowDays)for(const topicId of event.topicIds??[]){const topic=context.topics.find(item=>item.id===topicId);if(topic){const hours=(start-nowMs)/3_600_000,bonus=hours<=24?80:hours<=72?50:20,weak=Math.min((100-(progressFor(topic.id,context.progress)?.masteryScore??0))*.2,20);candidates.push(make(topic,"upcoming_event",config.eventBand+bonus+weak,`El evento “${event.title}” está próximo y este tema está vinculado.`,now,context.progress,[event.id],start));}}}
  for(const progress of context.progress){if(progress.reviewDueAt&&Date.parse(progress.reviewDueAt)<nowMs){const topic=context.topics.find(item=>item.id===progress.topicId);if(topic){const overdueDays=(nowMs-Date.parse(progress.reviewDueAt))/86_400_000;candidates.push(make(topic,"review_due",config.reviewBand+Math.min(overdueDays*5,50),"El repaso programado para este tema está vencido.",now,context.progress));}}}
  for(const topic of context.topics)for(const prerequisiteId of topic.prerequisiteTopicIds){const prerequisite=context.topics.find(item=>item.id===prerequisiteId),progress=progressFor(prerequisiteId,context.progress);if(prerequisite&&progress?.status!=="understood"&&progress?.status!=="mastered")candidates.push(make(prerequisite,"weak_prerequisite",config.prerequisiteBand+Math.min(100-(progress?.masteryScore??0),50),`Este tema es un prerrequisito débil para “${topic.title}”.`,now,context.progress,[topic.id]));}
  for(const session of context.sessions??[]){if(!session.endedAt&&(nowMs-Date.parse(session.startedAt))/3_600_000<=config.recentSessionWindowHours){const hours=(nowMs-Date.parse(session.startedAt))/3_600_000,topic=context.topics.find(item=>item.id===session.topicIds[0]);if(topic)candidates.push(make(topic,"continue_recent",config.continuationBand+(hours<2?20:hours<8?10:0),"Continúa la sesión de estudio que comenzaste recientemente.",now,context.progress,[session.id]));}}
  const next=context.topics.filter(topic=>progressFor(topic.id,context.progress)?.status!=="mastered").sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id))[0];
  if(next)candidates.push(make(next,"next_sequential",config.sequentialBand,"Es el siguiente tema pendiente en el orden del curso.",now,context.progress));
  return candidates.sort((a,b)=>b.priorityScore-a.priorityScore||a.mastery-b.mastery||a.eventTime-b.eventTime||a.topicOrder-b.topicOrder||a.topicId.localeCompare(b.topicId)).map(item=>({id:item.id,topicId:item.topicId,reasonCode:item.reasonCode,priorityScore:item.priorityScore,reasonText:item.reasonText,estimatedMinutes:item.estimatedMinutes,generatedAt:item.generatedAt,supportingIds:item.supportingIds}));
}

export function getNextStudyAction(context:RecommendationContext,config:RecommendationConfig):Recommendation|null{return generateRecommendations(context,config)[0]??null;}
