import {test,expect} from "@playwright/test";
test("KG-01/05/06 tablet graph offline, inspect, navigate, mastery and return",async({page,context})=>{
 await page.setViewportSize({width:820,height:1180});await page.goto("/");await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.goto("/knowledge-map");
 await expect(page.getByRole("heading",{name:"Knowledge Map",exact:true})).toBeVisible();await expect(page.locator(".react-flow__node")).toHaveCount(21);
 await page.getByLabel("Topic o Concept").selectOption("radio-spectrum");await page.getByLabel("Inspeccionar relación").selectOption("curriculum-path-3");await expect(page.getByRole("status")).toContainText("derived_from_curriculum");await page.getByRole("link",{name:"Abrir Topic",exact:true}).click();await expect(page.getByRole("heading",{name:"Espectro radioeléctrico y bandas de frecuencia",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Mark as Studied"}).click();await expect(page.getByTestId("mastery-score")).toHaveText("10/100");await page.getByRole("link",{name:"Volver a Knowledge Map"}).click();await page.getByLabel("Topic o Concept").selectOption("fund-radio-spectrum-bands");await expect(page.getByTestId("graph-mastery")).toHaveText("Mastery: 10/100 · studying");await page.reload();await page.getByLabel("Topic o Concept").selectOption("fund-radio-spectrum-bands");await expect(page.getByTestId("graph-mastery")).toHaveText("Mastery: 10/100 · studying");
 await page.screenshot({path:"test-results/knowledge-map-tablet.png",fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test("canonical course has eight Topics and no duplicate legacy block",async({page})=>{await page.goto("/courses/fundamentals-uas");await expect(page.getByRole("link",{name:"Start Study"})).toHaveCount(8);await expect(page.locator('a[href="/study/fund-radio-links-intro"]')).toHaveCount(0);await page.getByRole("link",{name:"Start Study"}).first().click();await expect(page.getByRole("heading",{name:"Tipos de UAS",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Learning objectives — adaptación pedagógica",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Finalizar Quiz"})).toHaveCount(0);});
