import {courseAcademic as a} from "@/lib/content/foundation";
export function AcademicDetails(){return <details className="mt-5 rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Guía académica y procedencia</summary><div className="mt-4 space-y-4"><p>{a.course_purpose.normalized_display_text}</p><p>Currículo: official_current. Material técnico: pending_course_material. Próxima fuente: Campus Virtual autorizado.</p><a href={a.source.url} style={{textDecoration:"underline"}}>Guía USC 2026/2027 (enlace externo)</a><p className="text-sm">Referencia 2023/2024 conservada como histórica. Las notas y evidencias personales no son calificaciones académicas.</p>
<details><summary>Resultados de aprendizaje oficiales · páginas 2–3</summary>{a.learning_outcomes.map(o=><div key={o.id} className="my-3"><p>{o.id}: {o.normalized_display_text}</p><p lang="gl">Original: {o.original_text}</p></div>)}</details>
<details><summary>Competencias · páginas 5–6</summary>{a.competencies.map(c=><div key={c.id} className="my-3"><p lang="gl">{c.original_text}</p><p>Páginas: {c.pages.join(", ")}</p>{c.ambiguity_note&&<p className="font-semibold">Nota de fuente: {c.ambiguity_note}</p>}</div>)}</details>
<details><summary>Prácticas · páginas 4 y 6</summary>{a.practices.map(p=><p className="my-3" key={p.id}>{p.normalized_display_text} · {p.technical_content_status}</p>)}<p>{a.practices[1].location?.normalized_display_text}. Ejecución pendiente de material autorizado.</p></details>
<details><summary>Evaluación académica · páginas 6–7</summary><p>Examen 20% · prácticas 75% · asistencia y participación 5%.</p><p>Umbral declarado: ≥ 5 puntos; denominador no indicado en ese párrafo.</p><p>La calificación académica y Mastery son sistemas independientes.</p></details>
<details><summary>Carga de trabajo: dos conjuntos distintos</summary><p>Página 1, ECTS Criterios/Memorias: tutorías 3 h, expositivas 12 h, interactivas 30 h; total declarado 45 h.</p><p>Página 7, estudio/trabajo personal: teoría 24+48 h, prácticas 16+52 h, tutorías 3+4 h, evaluación 3 h. Totales declarados: 46 h de contacto/actividad + 104 h personales = 150 h.</p><p>Se conserva la diferencia 45/46 sin conciliación.</p></details>
<details><summary>Metodología, bibliografía y recursos</summary><p>{a.methodology.normalized_display_text} (p. 6)</p>{a.bibliography.map(b=><p className="my-3" key={b.id}>{b.original_text} (p. {b.pages.join(", ")}) {b.ambiguity_note}</p>)}<p>Material técnico del Campus Virtual: aportaciones docentes de Universidad de Oviedo, Ingeniería Eléctrica (p. 4).</p><a href={a.study_resources[0].url} style={{textDecoration:"underline"}}>Canal del profesor recomendado por la guía (p. 7–8)</a><p>No hay vídeos asignados automáticamente a Topics.</p></details>
<details><summary>Ambigüedades conservadas del original</summary>{a.ambiguities.map(x=><p className="my-3" key={x.id}>{x.original_text} — {x.note} (p. {x.pages.join(", ")})</p>)}</details>
</div></details>;}
