"use client";
import { useEffect,useState } from "react";
import { Check,Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card,CardDescription,CardTitle } from "@/components/ui/card";
import { db } from "@/lib/db/db";
import { saveNote } from "@/lib/db/repositories/learning";
import { useProgress } from "@/features/progress/use-progress";
export function TopicActions({topicId}:{topicId:string}){const {progress,markStudied}=useProgress();const [note,setNote]=useState("");const [loaded,setLoaded]=useState(false);const [saving,setSaving]=useState(false);const [marking,setMarking]=useState(false);useEffect(()=>{let active=true;void db.notes.get(`note-${topicId}`).then(item=>{if(active){setNote(item?.body??"");setLoaded(true);}});return()=>{active=false;};},[topicId]);useEffect(()=>{if(!loaded)return;const timer=setTimeout(()=>{setSaving(true);void saveNote(topicId,note).finally(()=>setSaving(false));},500);return()=>clearTimeout(timer);},[loaded,note,topicId]);const item=progress[topicId];return <div className="sticky top-24 space-y-4"><Card><CardTitle>Progreso local</CardTitle><p className="mt-4 text-3xl font-bold" data-testid="mastery-score">{item?.masteryScore??0}/100</p><CardDescription>Estado: {item?.status??"pending"}. Estudiar aporta evidencia, no dominio total.</CardDescription><Button className="mt-5 w-full" disabled={marking} onClick={()=>{setMarking(true);void markStudied(topicId).finally(()=>setMarking(false));}}>{item?<Check size={17}/>:null}{marking?"Guardando…":item?"Studied · guardar evidencia":"Mark as Studied"}</Button></Card><Card><CardTitle>Notas personales</CardTitle><CardDescription>Guardadas únicamente en IndexedDB.</CardDescription><label htmlFor="topic-note" className="sr-only">Nota personal</label><textarea id="topic-note" value={note} disabled={!loaded} onChange={event=>setNote(event.target.value)} className="mt-4 min-h-40 w-full resize-y rounded-lg border p-3 disabled:opacity-60" placeholder={loaded?"Escribe una nota personal…":"Cargando nota…"}/><p className="mt-2 flex items-center gap-1 text-xs text-[#52635f]"><Save size={13}/>{saving?"Guardando…":loaded?"Guardado automático":"Cargando…"}</p></Card><Card><CardTitle>Recall y Practice</CardTitle><CardDescription>Pendientes de contenido oficial. No se muestran respuestas inventadas.</CardDescription><Button className="mt-4 w-full" variant="outline" disabled>Disponible en Active Study</Button></Card></div>;}
