import {it,expect} from "vitest";
import fs from "node:fs";
import {createHash} from "node:crypto";
import {courseAcademic as a,academicSources,academicRecords,canonicalBlocks,canonicalTopics} from "@/lib/content/foundation";
import {topics} from "@/lib/content/catalog";
import {graphNodes,graphEdges,validateGraph} from "@/lib/content/knowledge-graph";
import old from "@/content/courses/fundamentals-uas/foundation.v0.3.json";
import oldGraph from "@/content/courses/fundamentals-uas/knowledge-map.v0.3.json";
import {masteryConfig} from "@/lib/learning/config";
it("ACAD-01 current primary source",()=>expect([a.source.status,a.source.academic_year]).toEqual(["official_current","2026/2027"]));
it("ACAD-02 historical source retained",()=>expect(academicSources.some(s=>s.id===old.source.id&&s.status==="official_historical_reference")).toBe(true));
it("ACAD-03 four canonical blocks",()=>expect(canonicalBlocks.map(b=>b.id)).toEqual([1,2,3,4].map(n=>`fundamentals-block-0${n}`)));
it("ACAD-04 nineteen unique Topic IDs resolve to MDX",()=>{expect(canonicalTopics).toHaveLength(19);expect(new Set(canonicalTopics.map(t=>t.id)).size).toBe(19);for(const t of canonicalTopics)expect(fs.existsSync(t.contentRef)).toBe(true);});
it("ACAD-05 Block I IDs unchanged",()=>expect(canonicalTopics.filter(t=>t.blockId==="fundamentals-block-01").map(t=>t.id)).toEqual(old.topics.map(t=>t.stable_id)));
it("ACAD-06 legacy resolves outside canonical path",()=>{expect(topics.some(t=>t.id==="fund-radio-links-intro")).toBe(true);expect(canonicalTopics.some(t=>t.id==="fund-radio-links-intro")).toBe(false);});
it("ACAD-07 three official outcomes with original wording",()=>{expect(a.learning_outcomes.map(o=>o.id)).toEqual(["LO-FUND-01","LO-FUND-02","LO-FUND-03"]);for(const o of a.learning_outcomes)expect(o.original_text.length).toBeGreaterThan(30);});
it("ACAD-08 eleven competencies",()=>expect(a.competencies.map(c=>c.id)).toEqual(["CB6","CB7","CB10","CG1","CG3","CG4","CG5","CE1","CT6","CT8","CT9"]));
it("ACAD-09 academic grade independent of Mastery",()=>{expect(Object.values(a.assessment.weights)).toEqual([20,75,5]);expect(Object.values(masteryConfig.weights)).toEqual([10,20,35,25,10]);expect(a.assessment.passing_threshold.denominator).toBeNull();});
it("ACAD-10 workload provenance separate",()=>expect(a.workload_datasets.map(d=>d.pages)).toEqual([[1],[7]]));
it("ACAD-11 practices exist without invented execution",()=>{expect(a.practices.map(p=>p.id)).toEqual(["fund-practice-multirotor-sizing","fund-practice-flight"]);expect(a.practices.every(p=>p.technical_content_status==="pending_course_material")).toBe(true);});
it("ACAD-13 graph references valid",()=>{expect(validateGraph()).toEqual([]);expect(validateGraph(graphNodes,[{...graphEdges[0],targetId:"missing"}])).not.toEqual([]);});
it("ACAD-14 every derived edge has source and rationale",()=>{for(const edge of graphEdges){expect(academicSources.some(s=>s.id===edge.sourceRef)).toBe(true);expect(edge.rationale.length).toBeGreaterThan(20);expect(edge.provenance).toBe("derived_from_curriculum");}});
it("ACAD-17 gaps explicit for every canonical Topic",()=>{for(const t of academicRecords){expect(t.technical_content_status).toBe("pending_course_material");expect(fs.readFileSync(t.content_ref,"utf8")).toContain("Campus Virtual");}});
it("ACAD-19 CG3 anomaly retained",()=>{const c=a.competencies.find(c=>c.id==="CG3")!;expect(c.original_text).toContain("empresa que non pertenza a dous sistemas");expect(c.ambiguity_note).toBeTruthy();});
it("ACAD-20 CT8 anomaly retained",()=>{const c=a.competencies.find(c=>c.id==="CT8")!;expect(c.original_text).toContain("analizar e sentarse");expect(c.normalized_display_text).toBeNull();});
it("ACAD-21 45 and 46 coexist",()=>{expect(a.workload_datasets[0].declared_total).toBe(45);expect(a.workload_datasets[1].declared_contact_activity).toBe(46);});
it("ACAD-22 verified original PDF hash",()=>expect(createHash("sha256").update(fs.readFileSync(a.source.source_file)).digest("hex")).toBe("d37464d16f7684f86ba7ee9a56917e3854e2f2cbcafaf37b3ee59dcc503e7d33"));
it("ACAD-23 old graph nodes and edges remain intact",()=>{expect(graphNodes).toEqual(expect.arrayContaining(oldGraph.nodes));expect(graphEdges).toEqual(expect.arrayContaining(oldGraph.edges));});
it("ACAD-24 all new edges use current source",()=>{const oldIds=new Set(oldGraph.edges.map(e=>e.id));expect(graphEdges.filter(e=>!oldIds.has(e.id)).every(e=>e.sourceRef===a.source.id)).toBe(true);});
