"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {ReactFlow,Background,Controls,MiniMap,MarkerType,type Node,type Edge} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import {graphNodes,graphEdges,topicGraphState} from "@/lib/content/knowledge-graph";
import {academicSource,academicSources,canonicalTopics} from "@/lib/content/foundation";
import {useProgress} from "@/features/progress/use-progress";
const colors:Record<string,string>={pending:"#f1f5f9",studying:"#dbeafe",understood:"#d1fae5",mastered:"#ede9fe",reinforce:"#fef3c7"};
export function KnowledgeMap(){
  const {progress,hydrated}=useProgress();
  const [selected,setSelected]=useState(graphNodes[0].id);
  const [edgeId,setEdgeId]=useState<string>();
  const node=graphNodes.find(n=>n.id===selected)!;
  const relation=graphEdges.find(e=>e.id===edgeId);
  const nodes=useMemo<Node[]>(()=>graphNodes.map((n)=>{const state=topicGraphState(progress[n.topicId]);return {id:n.id,position:n.kind==="topic"?{x:0,y:canonicalTopics.findIndex(t=>t.id===n.topicId)*130}:{x:380,y:graphNodes.filter(x=>x.kind==="concept").findIndex(x=>x.id===n.id)*100},data:{label:<div><strong>{n.title}</strong><div>{n.kind==="topic"?`Topic · ${hydrated?`${state.score}/100 · ${state.status}`:"Cargando progreso…"}`:"Concept · sin score de dominio"}</div></div>},style:{width:270,background:n.kind==="topic"?colors[state.status]:"#fff",border:n.id===selected?"3px solid #185d52":"1px solid #64748b"},ariaLabel:`${n.kind}: ${n.title}`,selected:n.id===selected};}),[progress,selected,hydrated]);
  const edges=useMemo<Edge[]>(()=>graphEdges.map(e=>({id:e.id,source:e.sourceId,target:e.targetId,markerEnd:{type:MarkerType.ArrowClosed},style:{stroke:e.id===edgeId?"#185d52":"#94a3b8",strokeWidth:e.id===edgeId?3:1.5,strokeDasharray:e.relationType==="related_to"?"5 4":undefined},label:e.id===edgeId?e.relationType:undefined})),[edgeId]);
  return <div className="space-y-5"><h1 className="text-3xl font-bold">Knowledge Map</h1><p>Bloques I–IV · Guía oficial USC 2026/2027. Ruta pedagógica propuesta; las flechas no son prerrequisitos oficiales ni una cadena física de comunicación.</p><p>Solo los Topics muestran mastery. Los Concepts representan estructura académica.</p><div className="flex flex-wrap gap-3 text-sm" aria-label="Leyenda de mastery">{Object.entries(colors).map(([status,color])=><span key={status} className="rounded border px-3 py-2" style={{background:color}}>{status}</span>)}</div>
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_300px]"><section aria-label="Grafo académico" data-testid="knowledge-graph" className="h-[65vh] min-h-[420px] overflow-hidden rounded-xl border bg-white"><ReactFlow nodes={nodes} edges={edges} onNodeClick={(_,n)=>{setSelected(n.id);setEdgeId(undefined);}} onEdgeClick={(_,e)=>{setEdgeId(e.id);}} nodesDraggable={false} nodesConnectable={false} edgesReconnectable={false} deleteKeyCode={null} minZoom={.2} maxZoom={2} fitView fitViewOptions={{padding:.15}}><Background/><Controls showInteractive={false}/><MiniMap pannable zoomable/></ReactFlow></section>
    <aside className="space-y-4 rounded-xl border bg-white p-4"><h2 className="text-lg font-bold">Explorar nodo</h2><label htmlFor="graph-node">Topic o Concept</label><select id="graph-node" className="min-h-11 w-full rounded border p-2" value={selected} onChange={e=>{setSelected(e.target.value);setEdgeId(undefined);}}>{graphNodes.map(n=><option key={n.id} value={n.id}>{n.kind}: {n.title}</option>)}</select><h3 className="font-semibold">{node.title}</h3><p data-testid="graph-mastery">{node.kind==="topic"?`Mastery: ${topicGraphState(progress[node.topicId]).score}/100 · ${topicGraphState(progress[node.topicId]).status}`:"Concept académico · sin mastery propio"}</p>{node.status&&<p>Contenido: {node.status}</p>}<Link style={{color:"#fff"}} className="block min-h-11 rounded bg-[#185d52] px-4 py-3 text-white" href={`/study/${node.topicId}`}>Abrir Topic</Link>
    <label htmlFor="graph-relation" className="block">Inspeccionar relación</label><select id="graph-relation" className="min-h-11 w-full rounded border p-2" value={edgeId??""} onChange={e=>setEdgeId(e.target.value||undefined)}><option value="">Selecciona una relación</option>{graphEdges.filter(e=>e.sourceId===selected||e.targetId===selected).map(e=><option value={e.id} key={e.id}>{graphNodes.find(n=>n.id===e.sourceId)?.title} → {graphNodes.find(n=>n.id===e.targetId)?.title}</option>)}</select>
    {relation&&<div role="status"><p>{relation.relationType}</p><p>Procedencia: {relation.provenance}</p><p>{relation.rationale}</p><p>Estado de fuente: {academicSources.find(s=>s.id===relation.sourceRef)?.status}</p><p>Fuente: {relation.sourceRef} · páginas {(relation.source_pages??[1]).join(", ")}</p></div>}<p className="text-sm">Línea discontinua: relación conceptual. Línea continua: agrupación en un Topic. Acerca el mapa con los controles o un gesto de pinza.</p><a href={academicSource.url} className="underline">Fuente académica actual (requiere conexión)</a></aside></div>
  </div>;
}
